### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by cooperaj** [thomaswelton/laravel-gravatar#14]
Can we please get an update to the composer file for Laravel 5 support? Since the HTML component has been moved to it's own external dependancy the laravel/support line will likely need to be changed wholesale for

    "illuminate/html": "~5.0",

**Comment by UnrulyNatives** [comment]
Hi,

any chances for the Laravel 5 version?

**Comment by thulaban** [comment]
![gravatar for laravel](https://cloud.githubusercontent.com/assets/7749551/6005416/26b8628e-ab30-11e4-9b16-aa014f82625b.PNG)
getting error while pulling package from laravel 5 application. laravel-gravatar requires /illuminate/support 5.0 to support laravel 5 applications.

It would be great if support is provided for laravel 5.
thank you.

**Comment by cooperaj** [comment]
If you can handle not using packagist my branch works (did work)

 	"require": {
                "thomaswelton/laravel-gravatar": "dev-l5-compat as 1.0.x-dev"
 	},
        "repositories": [
                {
                        "type": "vcs",
                        "url":  "https://github.com/cooperaj/laravel-gravatar"
                }
        ],

**Comment by UnrulyNatives** [comment]
I get this error: 
Call to undefined method [package]

In case of intervention/image this package solved my problem:
 "morrislaptop/laravel-five-package-bridges": "dev-master"

**Comment by janareit** [comment]
Would love to have it for L5 as well...

**Comment by AntoineAugusti** [comment]
I've just opened a PR to do that. Check #17

**Comment by thomaswelton** [comment]
Thanks @AntoineAugusti I'll check it out and merge ASAP. Thanks for the contribution.

**Comment by thomaswelton** [comment]
Fixed by #17
