### ISSUE TITLE
Suggesting twig?

### ISSUE THREAD

**Issue by Padrio** [thomaswelton/laravel-gravatar#16]
vagrant@scotchbox:/var/www$ composer update                   
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing thomaswelton/gravatarlib (0.1.0)
    Downloading: 100%         

  - Installing thomaswelton/laravel-gravatar (0.1.0)
    Downloading: 100%         

thomaswelton/gravatarlib suggests installing twig/twig (>=1.4.0)
Writing lock file
Generating autoload files
Generating optimized class loader
vagrant@scotchbox:/var/www$ composer update                   
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing thomaswelton/gravatarlib (0.1.0)
    Downloading: 100%         

  - Installing thomaswelton/laravel-gravatar (0.1.0)
    Downloading: 100%         

thomaswelton/gravatarlib suggests installing twig/twig (>=1.4.0)
Writing lock file
Generating autoload files
Generating optimized class loader

Could someone explain my why it is suggesting me to install twig?

**Comment by Morialkar** [comment]
Easy one, [thomaswelton/gravatarlib](https://github.com/thomaswelton/gravatarlib) is a fork of [emberlabs/gravatarlib](https://github.com/emberlabs/gravatarlib) and it includes Twig integration, so I guess they really love Twig and want to boost adoption.
