### ISSUE TITLE
Allow override of Gravatar's default avatar

### ISSUE THREAD

**Issue by bkuhl** [thomaswelton/laravel-gravatar#19]
Gravatar's default avatars aren't great.  It'd be fantastic if we could provide an image that's to be used as the default Gravatar in the event there isn't one.  According to https://tommcfarlin.com/check-if-a-user-has-a-gravatar/ the http response header of the gravatar URL will indicate whether the user has a Gravatar.

**Comment by AntoineAugusti** [comment]
I guess you can use something like this to implement this behaviour:

```php
function gravatar($email) {
    if (Gravatar::exists($email)) {
        return Gravatar::src($email);
    }
    return 'https://example.com/foo.png'
}

```

**Comment by mattzuba** [comment]
Gravatar's 'default' option accepts a URL-encoded url that can be used as a default as well, so this functionality is really already built in.

https://en.gravatar.com/site/implement/images/#default-image

**Comment by AntoineAugusti** [comment]
OK, I'll try to take a look this week. As always, pull requests are welcome.

**Comment by mattzuba** [comment]
Sorry, I guess I wasn't clear.  The codebase of this 'plugin' already supports this.

Set 'default' in config/gravatar.php to whatever you want your default image to be and that's it.

**Comment by AntoineAugusti** [comment]
Yeah, I saw that. But the documentation needs to be updated to reflect
this. I've a pull request opened also that adds unit tests so I'll a test
case for this.

Thanks!

**Comment by AntoineAugusti** [comment]
@mattzuba @bkuhl Added in the last 2 commits of https://github.com/thomaswelton/laravel-gravatar/pull/20

**Comment by bkuhl** [comment]
Awesome, thanks @AntoineAugusti!
