### ISSUE TITLE
Method buildGravatarURL doesn't exist?

### ISSUE THREAD

**Issue by usefulz** [thomaswelton/laravel-gravatar#23]
Looks like calls to $this->buildGravatarURL($email) doesn't work because the method isn't defined.

https://github.com/thomaswelton/laravel-gravatar/search?utf8=%E2%9C%93&q=buildGravatarURL

**Comment by thomaswelton** [comment]
The Gravatar class extends the GravatarLib so the method is here https://github.com/thomaswelton/gravatarlib/blob/master/Gravatar.php#L227
