### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by Yo1L** [thomaswelton/laravel-gravatar#30]
Hello,

Do you plan to upgrade to Laravel 6 ?

Thx for your work

**Comment by thomaswelton** [comment]
I'm no longer actively working with Laravel. But PR's and maintainers for this project would be welcomed

**Comment by wells** [comment]
Hi @thomaswelton I have added pull #33. Can we get this merged please? Thanks.

HHVM was breaking on the other pull request that was opened by @robbens. It also looks to be common practice to future proof packages for Laravel 7, in advance of release.

**Comment by thomaswelton** [comment]
@wells Merged and tagged a `1.2.0` release.
